### PR TITLE
revert: @node-rs/argon2 -> node-argon2

### LINKED ISSUE #4804: [Bug]: Cannot find module '@node-rs/argon2-linux-arm64-gnu'
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

-  Web Browser: Firefox 96.0.3 (64-bit)
-  Local OS: macOS 10.14.6 (Mojave)
-  Remote OS: [Debian bullseye](https://hub.docker.com/_/debian)
-  Remote Architecture: aarch64
-  `code-server --version`: code-server 4.0.2 5cdfe74686aa73e023f8354a9a6014eb30caa7dd

### Steps to Reproduce

1.  `git clone https://gitlab.b-data.ch/jupyterlab/julia/docker-stack.git`
2.  `cd docker-stack/ver`
3.  `docker build -t julia-ver -f latest.Dockerfile .`

### Expected

Successful build

### Actual

https://gitlab.b-data.ch/jupyterlab/r/r-ver/-/jobs/20883

### Logs

```
[...]

Error: Cannot find module '@node-rs/argon2-linux-arm64-gnu'
Require stack:
- /opt/code-server/node_modules/@node-rs/argon2/index.js
- /opt/code-server/out/node/util.js
- /opt/code-server/out/node/cli.js
- /opt/code-server/out/node/entry.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/opt/code-server/node_modules/@node-rs/argon2/index.js:172:31)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/code-server/node_modules/@node-rs/argon2/index.js',
    '/opt/code-server/out/node/util.js',
    '/opt/code-server/out/node/cli.js',
    '/opt/code-server/out/node/entry.js'
  ]
}

[...]
```

### Screenshot/Video

_No response_

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Related issues:

*  https://github.com/coder/code-server/issues/4422
*  https://github.com/coder/code-server/pull/4733

### PR DESCRIPTION
**Pull request by jsjoeio**
This reverts part of the changes introduced in refactor: migrate from argon2 ->
@node-rs/argon2 (#4733)

Switching to @node-rs/argon2 introduced bugs that we couldn't solve due to
limitations in npm.

see here
https://github.com/coder/code-server/issues/4804#issuecomment-1030338395

Fixes #4804

### CODE REVIEW

File: src/node/util.ts [hunk 1]
```diff
@@ -170,8 +169,7 @@ export const isHashMatch = async (password: string, hash: string) => {
   try {
     return await argon2.verify(hash, password)
   } catch (error: any) {
-    logger.error(error)
-    return false
+    throw new Error(error)
```
Comment (code-asher) [inline src/node/util.ts:172]: Could remove the try/catch since this just re-throws.

**Review by code-asher — APPROVED** [review]

File: src/node/util.ts (hunk 1 above)
Comment (jsjoeio) [reply src/node/util.ts:172]: Ah, you're saying since `argon2` throws? Good point.
